[plugins.biome]
enabled = true
mode = "monitor"

[plugins.maintainability]
enabled = true
mode = "block"

[plugins.coverage]
enabled = true
mode = "block"

[plugins.format]
enabled = false

# Disable formatters that error on non-UTF8 streams in CI
[plugins.prettier]
enabled = false

[plugins.markdownlint]
enabled = false
