import type { CuratedCatalogEntry } from "./build";
import { buildCatalog } from "./build";

const entries: CuratedCatalogEntry[] = [
  { title: "Pride and Prejudice", authors: ["Jane Austen"] },
  { title: "Emma", authors: ["Jane Austen"] },
  { title: "Sense and Sensibility", authors: ["Jane Austen"] },
  { title: "Persuasion", authors: ["Jane Austen"] },
  { title: "Mansfield Park", authors: ["Jane Austen"] },
  { title: "Northanger Abbey", authors: ["Jane Austen"] },
  { title: "Jane Eyre", authors: ["Charlotte Bronte"] },
  { title: "Wuthering Heights", authors: ["Emily Bronte"] },
  { title: "Great Expectations", authors: ["Charles Dickens"] },
  { title: "David Copperfield", authors: ["Charles Dickens"] },
  { title: "Oliver Twist", authors: ["Charles Dickens"] },
  { title: "A Tale of Two Cities", authors: ["Charles Dickens"] },
  { title: "Bleak House", authors: ["Charles Dickens"] },
  { title: "Middlemarch", authors: ["George Eliot"] },
  { title: "Tess of the d'Urbervilles", authors: ["Thomas Hardy"] },
  { title: "Far from the Madding Crowd", authors: ["Thomas Hardy"] },
  { title: "The Return of the Native", authors: ["Thomas Hardy"] },
  { title: "Moby-Dick", authors: ["Herman Melville"] },
  { title: "The Scarlet Letter", authors: ["Nathaniel Hawthorne"] },
  { title: "Little Women", authors: ["Louisa May Alcott"] },
  { title: "Anna Karenina", authors: ["Leo Tolstoy"] },
  { title: "War and Peace", authors: ["Leo Tolstoy"] },
  { title: "Crime and Punishment", authors: ["Fyodor Dostoevsky"] },
  { title: "The Brothers Karamazov", authors: ["Fyodor Dostoevsky"] },
  { title: "The Idiot", authors: ["Fyodor Dostoevsky"] },
  { title: "Notes from Underground", authors: ["Fyodor Dostoevsky"] },
  { title: "Fathers and Sons", authors: ["Ivan Turgenev"] },
  { title: "Madame Bovary", authors: ["Gustave Flaubert"] },
  { title: "The Count of Monte Cristo", authors: ["Alexandre Dumas"] },
  { title: "Les Miserables", authors: ["Victor Hugo"] },
  { title: "The Hunchback of Notre-Dame", authors: ["Victor Hugo"] },
  { title: "Don Quixote", authors: ["Miguel de Cervantes"] },
  { title: "Ulysses", authors: ["James Joyce"] },
  { title: "Dubliners", authors: ["James Joyce"] },
  { title: "A Portrait of the Artist as a Young Man", authors: ["James Joyce"] },
  { title: "The Odyssey", authors: ["Homer"] },
  { title: "The Iliad", authors: ["Homer"] },
  { title: "The Aeneid", authors: ["Virgil"] },
  { title: "The Divine Comedy", authors: ["Dante Alighieri"] },
  { title: "Paradise Lost", authors: ["John Milton"] },
  { title: "Candide", authors: ["Voltaire"] },
  { title: "Gulliver's Travels", authors: ["Jonathan Swift"] },
  { title: "Robinson Crusoe", authors: ["Daniel Defoe"] },
  { title: "Frankenstein", authors: ["Mary Shelley"] },
  { title: "Dracula", authors: ["Bram Stoker"] },
  { title: "The Picture of Dorian Gray", authors: ["Oscar Wilde"] },
  { title: "Heart of Darkness", authors: ["Joseph Conrad"] },
  { title: "Lord Jim", authors: ["Joseph Conrad"] },
  { title: "The Age of Innocence", authors: ["Edith Wharton"] },
  { title: "Ethan Frome", authors: ["Edith Wharton"] },
  { title: "The Call of the Wild", authors: ["Jack London"] },
  { title: "White Fang", authors: ["Jack London"] },
  { title: "East of Eden", authors: ["John Steinbeck"] },
  { title: "The Grapes of Wrath", authors: ["John Steinbeck"] },
  { title: "Of Mice and Men", authors: ["John Steinbeck"] },
  { title: "The Sun Also Rises", authors: ["Ernest Hemingway"] },
  { title: "A Farewell to Arms", authors: ["Ernest Hemingway"] },
  { title: "For Whom the Bell Tolls", authors: ["Ernest Hemingway"] },
  { title: "The Old Man and the Sea", authors: ["Ernest Hemingway"] },
  { title: "Catch-22", authors: ["Joseph Heller"] },
  { title: "The Sound and the Fury", authors: ["William Faulkner"] },
  { title: "As I Lay Dying", authors: ["William Faulkner"] },
  { title: "Absalom, Absalom!", authors: ["William Faulkner"] },
  { title: "Beloved", authors: ["Toni Morrison"] },
  { title: "Their Eyes Were Watching God", authors: ["Zora Neale Hurston"] },
  { title: "Invisible Man", authors: ["Ralph Ellison"] },
  { title: "Native Son", authors: ["Richard Wright"] },
  { title: "Go Tell It on the Mountain", authors: ["James Baldwin"] },
  { title: "To the Lighthouse", authors: ["Virginia Woolf"] },
  { title: "Mrs Dalloway", authors: ["Virginia Woolf"] },
  { title: "Orlando", authors: ["Virginia Woolf"] },
  { title: "The Waves", authors: ["Virginia Woolf"] },
  { title: "The Secret Garden", authors: ["Frances Hodgson Burnett"] },
  { title: "Anne of Green Gables", authors: ["L. M. Montgomery"] },
  { title: "The Wind in the Willows", authors: ["Kenneth Grahame"] },
  { title: "Treasure Island", authors: ["Robert Louis Stevenson"] },
  { title: "Kidnapped", authors: ["Robert Louis Stevenson"] },
  { title: "The Red and the Black", authors: ["Stendhal"] },
  { title: "Germinal", authors: ["Emile Zola"] },
  { title: "The Trial", authors: ["Franz Kafka"] },
  { title: "The Castle", authors: ["Franz Kafka"] },
  { title: "The Metamorphosis", authors: ["Franz Kafka"] },
  { title: "The Stranger", authors: ["Albert Camus"] },
  { title: "The Plague", authors: ["Albert Camus"] },
  { title: "Things Fall Apart", authors: ["Chinua Achebe"] },
  { title: "The Good Earth", authors: ["Pearl S. Buck"] },
  { title: "One Hundred Years of Solitude", authors: ["Gabriel Garcia Marquez"] },
  { title: "Love in the Time of Cholera", authors: ["Gabriel Garcia Marquez"] },
  { title: "Pedro Paramo", authors: ["Juan Rulfo"] },
  { title: "Wide Sargasso Sea", authors: ["Jean Rhys"] },
  { title: "The Master and Margarita", authors: ["Mikhail Bulgakov"] },
  { title: "Doctor Zhivago", authors: ["Boris Pasternak"] },
  { title: "Uncle Tom's Cabin", authors: ["Harriet Beecher Stowe"] },
  { title: "My Antonia", authors: ["Willa Cather"] },
  { title: "The Awakening", authors: ["Kate Chopin"] },
  { title: "Siddhartha", authors: ["Hermann Hesse"] },
  { title: "Steppenwolf", authors: ["Hermann Hesse"] },
  { title: "The House of Mirth", authors: ["Edith Wharton"] },
  { title: "A Room with a View", authors: ["E. M. Forster"] },
  { title: "The Portrait of a Lady", authors: ["Henry James"] },
];

export const classicsCatalog = buildCatalog("Classics", entries);

export default classicsCatalog;
