import type { CuratedCatalogEntry } from "./build";
import { buildCatalog } from "./build";

const entries: CuratedCatalogEntry[] = [
  { title: "The Hobbit", authors: ["J. R. R. Tolkien"] },
  { title: "The Fellowship of the Ring", authors: ["J. R. R. Tolkien"] },
  { title: "The Two Towers", authors: ["J. R. R. Tolkien"] },
  { title: "The Return of the King", authors: ["J. R. R. Tolkien"] },
  { title: "The Silmarillion", authors: ["J. R. R. Tolkien"] },
  { title: "The Name of the Wind", authors: ["Patrick Rothfuss"] },
  { title: "The Wise Man's Fear", authors: ["Patrick Rothfuss"] },
  { title: "The Way of Kings", authors: ["Brandon Sanderson"] },
  { title: "Words of Radiance", authors: ["Brandon Sanderson"] },
  { title: "Oathbringer", authors: ["Brandon Sanderson"] },
  { title: "Rhythm of War", authors: ["Brandon Sanderson"] },
  { title: "Mistborn: The Final Empire", authors: ["Brandon Sanderson"] },
  { title: "The Well of Ascension", authors: ["Brandon Sanderson"] },
  { title: "The Hero of Ages", authors: ["Brandon Sanderson"] },
  { title: "Warbreaker", authors: ["Brandon Sanderson"] },
  { title: "Elantris", authors: ["Brandon Sanderson"] },
  { title: "The Eye of the World", authors: ["Robert Jordan"] },
  { title: "The Great Hunt", authors: ["Robert Jordan"] },
  { title: "The Dragon Reborn", authors: ["Robert Jordan"] },
  { title: "The Shadow Rising", authors: ["Robert Jordan"] },
  { title: "The Fires of Heaven", authors: ["Robert Jordan"] },
  { title: "Lord of Chaos", authors: ["Robert Jordan"] },
  { title: "A Game of Thrones", authors: ["George R. R. Martin"] },
  { title: "A Clash of Kings", authors: ["George R. R. Martin"] },
  { title: "A Storm of Swords", authors: ["George R. R. Martin"] },
  { title: "A Feast for Crows", authors: ["George R. R. Martin"] },
  { title: "A Dance with Dragons", authors: ["George R. R. Martin"] },
  { title: "The Blade Itself", authors: ["Joe Abercrombie"] },
  { title: "Before They Are Hanged", authors: ["Joe Abercrombie"] },
  { title: "Last Argument of Kings", authors: ["Joe Abercrombie"] },
  { title: "Best Served Cold", authors: ["Joe Abercrombie"] },
  { title: "The Lies of Locke Lamora", authors: ["Scott Lynch"] },
  { title: "Red Seas Under Red Skies", authors: ["Scott Lynch"] },
  { title: "The Republic of Thieves", authors: ["Scott Lynch"] },
  { title: "Assassin's Apprentice", authors: ["Robin Hobb"] },
  { title: "Royal Assassin", authors: ["Robin Hobb"] },
  { title: "Assassin's Quest", authors: ["Robin Hobb"] },
  { title: "Ship of Magic", authors: ["Robin Hobb"] },
  { title: "Mad Ship", authors: ["Robin Hobb"] },
  { title: "Ship of Destiny", authors: ["Robin Hobb"] },
  { title: "Gardens of the Moon", authors: ["Steven Erikson"] },
  { title: "Deadhouse Gates", authors: ["Steven Erikson"] },
  { title: "Memories of Ice", authors: ["Steven Erikson"] },
  { title: "House of Chains", authors: ["Steven Erikson"] },
  { title: "Midnight Tides", authors: ["Steven Erikson"] },
  { title: "The Black Prism", authors: ["Brent Weeks"] },
  { title: "The Blinding Knife", authors: ["Brent Weeks"] },
  { title: "The Broken Eye", authors: ["Brent Weeks"] },
  { title: "The Blood Mirror", authors: ["Brent Weeks"] },
  { title: "The Burning White", authors: ["Brent Weeks"] },
  { title: "Jonathan Strange & Mr Norrell", authors: ["Susanna Clarke"] },
  { title: "Stardust", authors: ["Neil Gaiman"] },
  { title: "American Gods", authors: ["Neil Gaiman"] },
  { title: "Neverwhere", authors: ["Neil Gaiman"] },
  { title: "Good Omens", authors: ["Neil Gaiman", "Terry Pratchett"] },
  { title: "The Last Wish", authors: ["Andrzej Sapkowski"] },
  { title: "Sword of Destiny", authors: ["Andrzej Sapkowski"] },
  { title: "Blood of Elves", authors: ["Andrzej Sapkowski"] },
  { title: "Time of Contempt", authors: ["Andrzej Sapkowski"] },
  { title: "Baptism of Fire", authors: ["Andrzej Sapkowski"] },
  { title: "The Tower of the Swallow", authors: ["Andrzej Sapkowski"] },
  { title: "The Lady of the Lake", authors: ["Andrzej Sapkowski"] },
  { title: "The Sword of Shannara", authors: ["Terry Brooks"] },
  { title: "The Elfstones of Shannara", authors: ["Terry Brooks"] },
  { title: "The Wishsong of Shannara", authors: ["Terry Brooks"] },
  { title: "The Once and Future King", authors: ["T. H. White"] },
  { title: "The Last Unicorn", authors: ["Peter S. Beagle"] },
  { title: "A Wizard of Earthsea", authors: ["Ursula K. Le Guin"] },
  { title: "The Tombs of Atuan", authors: ["Ursula K. Le Guin"] },
  { title: "The Farthest Shore", authors: ["Ursula K. Le Guin"] },
  { title: "Tehanu", authors: ["Ursula K. Le Guin"] },
  { title: "The Golden Compass", authors: ["Philip Pullman"] },
  { title: "The Subtle Knife", authors: ["Philip Pullman"] },
  { title: "The Amber Spyglass", authors: ["Philip Pullman"] },
  { title: "Sabriel", authors: ["Garth Nix"] },
  { title: "Lirael", authors: ["Garth Nix"] },
  { title: "Abhorsen", authors: ["Garth Nix"] },
  { title: "The Priory of the Orange Tree", authors: ["Samantha Shannon"] },
  { title: "The Poppy War", authors: ["R. F. Kuang"] },
  { title: "The Dragon Republic", authors: ["R. F. Kuang"] },
  { title: "The Burning God", authors: ["R. F. Kuang"] },
  { title: "The Fifth Season", authors: ["N. K. Jemisin"] },
  { title: "The Obelisk Gate", authors: ["N. K. Jemisin"] },
  { title: "The Stone Sky", authors: ["N. K. Jemisin"] },
  { title: "Circe", authors: ["Madeline Miller"] },
  { title: "The Song of Achilles", authors: ["Madeline Miller"] },
  { title: "The Bear and the Nightingale", authors: ["Katherine Arden"] },
  { title: "Uprooted", authors: ["Naomi Novik"] },
  { title: "Spinning Silver", authors: ["Naomi Novik"] },
  { title: "The Night Circus", authors: ["Erin Morgenstern"] },
  { title: "The Starless Sea", authors: ["Erin Morgenstern"] },
  { title: "Tigana", authors: ["Guy Gavriel Kay"] },
  { title: "The Lions of Al-Rassan", authors: ["Guy Gavriel Kay"] },
  { title: "The Curse of Chalion", authors: ["Lois McMaster Bujold"] },
  { title: "Paladin of Souls", authors: ["Lois McMaster Bujold"] },
  { title: "The Grace of Kings", authors: ["Ken Liu"] },
  { title: "Jade City", authors: ["Fonda Lee"] },
  { title: "Jade War", authors: ["Fonda Lee"] },
  { title: "Jade Legacy", authors: ["Fonda Lee"] },
  { title: "The Bone Ships", authors: ["R. J. Barker"] },
];

export const fantasyCatalog = buildCatalog("Fantasy", entries);

export default fantasyCatalog;
