import type { CuratedCatalogEntry } from "./build";
import { buildCatalog } from "./build";

const entries: CuratedCatalogEntry[] = [
  { title: "A Study in Scarlet", authors: ["Arthur Conan Doyle"] },
  { title: "The Sign of Four", authors: ["Arthur Conan Doyle"] },
  { title: "The Adventures of Sherlock Holmes", authors: ["Arthur Conan Doyle"] },
  { title: "The Hound of the Baskervilles", authors: ["Arthur Conan Doyle"] },
  { title: "The Valley of Fear", authors: ["Arthur Conan Doyle"] },
  { title: "And Then There Were None", authors: ["Agatha Christie"] },
  { title: "The Murder of Roger Ackroyd", authors: ["Agatha Christie"] },
  { title: "Murder on the Orient Express", authors: ["Agatha Christie"] },
  { title: "Death on the Nile", authors: ["Agatha Christie"] },
  { title: "The ABC Murders", authors: ["Agatha Christie"] },
  { title: "Crooked House", authors: ["Agatha Christie"] },
  { title: "Evil Under the Sun", authors: ["Agatha Christie"] },
  { title: "The Moonstone", authors: ["Wilkie Collins"] },
  { title: "The Woman in White", authors: ["Wilkie Collins"] },
  { title: "The Big Sleep", authors: ["Raymond Chandler"] },
  { title: "Farewell, My Lovely", authors: ["Raymond Chandler"] },
  { title: "The Long Goodbye", authors: ["Raymond Chandler"] },
  { title: "The Maltese Falcon", authors: ["Dashiell Hammett"] },
  { title: "The Thin Man", authors: ["Dashiell Hammett"] },
  { title: "Strangers on a Train", authors: ["Patricia Highsmith"] },
  { title: "The Talented Mr. Ripley", authors: ["Patricia Highsmith"] },
  { title: "Ripley Under Ground", authors: ["Patricia Highsmith"] },
  { title: "Rebecca", authors: ["Daphne du Maurier"] },
  { title: "The Name of the Rose", authors: ["Umberto Eco"] },
  { title: "Tinker Tailor Soldier Spy", authors: ["John le Carre"] },
  { title: "Smiley's People", authors: ["John le Carre"] },
  { title: "The Spy Who Came in from the Cold", authors: ["John le Carre"] },
  { title: "The Day of the Jackal", authors: ["Frederick Forsyth"] },
  { title: "The Odessa File", authors: ["Frederick Forsyth"] },
  { title: "The Bourne Identity", authors: ["Robert Ludlum"] },
  { title: "The Bourne Supremacy", authors: ["Robert Ludlum"] },
  { title: "The Bourne Ultimatum", authors: ["Robert Ludlum"] },
  { title: "Presumed Innocent", authors: ["Scott Turow"] },
  { title: "The Firm", authors: ["John Grisham"] },
  { title: "The Pelican Brief", authors: ["John Grisham"] },
  { title: "A Time to Kill", authors: ["John Grisham"] },
  { title: "The Client", authors: ["John Grisham"] },
  { title: "The Lincoln Lawyer", authors: ["Michael Connelly"] },
  { title: "The Brass Verdict", authors: ["Michael Connelly"] },
  { title: "The Poet", authors: ["Michael Connelly"] },
  { title: "The Black Echo", authors: ["Michael Connelly"] },
  { title: "Mystic River", authors: ["Dennis Lehane"] },
  { title: "Gone, Baby, Gone", authors: ["Dennis Lehane"] },
  { title: "Shutter Island", authors: ["Dennis Lehane"] },
  { title: "Red Dragon", authors: ["Thomas Harris"] },
  { title: "The Silence of the Lambs", authors: ["Thomas Harris"] },
  { title: "Hannibal", authors: ["Thomas Harris"] },
  { title: "The Girl with the Dragon Tattoo", authors: ["Stieg Larsson"] },
  { title: "The Girl Who Played with Fire", authors: ["Stieg Larsson"] },
  { title: "The Girl Who Kicked the Hornets' Nest", authors: ["Stieg Larsson"] },
  { title: "Gone Girl", authors: ["Gillian Flynn"] },
  { title: "Sharp Objects", authors: ["Gillian Flynn"] },
  { title: "Dark Places", authors: ["Gillian Flynn"] },
  { title: "The Girl on the Train", authors: ["Paula Hawkins"] },
  { title: "Into the Water", authors: ["Paula Hawkins"] },
  { title: "Big Little Lies", authors: ["Liane Moriarty"] },
  { title: "In the Woods", authors: ["Tana French"] },
  { title: "The Likeness", authors: ["Tana French"] },
  { title: "Faithful Place", authors: ["Tana French"] },
  { title: "Broken Harbor", authors: ["Tana French"] },
  { title: "The Secret Place", authors: ["Tana French"] },
  { title: "The Trespasser", authors: ["Tana French"] },
  { title: "The Secret History", authors: ["Donna Tartt"] },
  { title: "Before I Go to Sleep", authors: ["S. J. Watson"] },
  { title: "The Silent Patient", authors: ["Alex Michaelides"] },
  { title: "The Maidens", authors: ["Alex Michaelides"] },
  { title: "In a Dark, Dark Wood", authors: ["Ruth Ware"] },
  { title: "The Woman in Cabin 10", authors: ["Ruth Ware"] },
  { title: "The Turn of the Key", authors: ["Ruth Ware"] },
  { title: "One by One", authors: ["Ruth Ware"] },
  { title: "The Guest List", authors: ["Lucy Foley"] },
  { title: "The Hunting Party", authors: ["Lucy Foley"] },
  { title: "The Paris Apartment", authors: ["Lucy Foley"] },
  { title: "Magpie Murders", authors: ["Anthony Horowitz"] },
  { title: "Moonflower Murders", authors: ["Anthony Horowitz"] },
  { title: "The Thursday Murder Club", authors: ["Richard Osman"] },
  { title: "The Man Who Died Twice", authors: ["Richard Osman"] },
  { title: "The Bullet That Missed", authors: ["Richard Osman"] },
  { title: "The Last Devil to Die", authors: ["Richard Osman"] },
  { title: "The Devotion of Suspect X", authors: ["Keigo Higashino"] },
  { title: "Malice", authors: ["Keigo Higashino"] },
  { title: "Salvation of a Saint", authors: ["Keigo Higashino"] },
  { title: "The Snowman", authors: ["Jo Nesbo"] },
  { title: "Headhunters", authors: ["Jo Nesbo"] },
  { title: "Tell No One", authors: ["Harlan Coben"] },
  { title: "Gone for Good", authors: ["Harlan Coben"] },
  { title: "The Stranger", authors: ["Harlan Coben"] },
  { title: "I Am Pilgrim", authors: ["Terry Hayes"] },
  { title: "The Chain", authors: ["Adrian McKinty"] },
  { title: "The Dry", authors: ["Jane Harper"] },
  { title: "Force of Nature", authors: ["Jane Harper"] },
  { title: "The Woman in the Window", authors: ["A. J. Finn"] },
  { title: "The Couple Next Door", authors: ["Shari Lapena"] },
  { title: "The Kind Worth Killing", authors: ["Peter Swanson"] },
  { title: "Behind Closed Doors", authors: ["B. A. Paris"] },
  { title: "The 7 1/2 Deaths of Evelyn Hardcastle", authors: ["Stuart Turton"] },
  { title: "The Appeal", authors: ["Janice Hallett"] },
  { title: "The Murder Room", authors: ["P. D. James"] },
  { title: "An Unsuitable Job for a Woman", authors: ["P. D. James"] },
  { title: "Cover Her Face", authors: ["P. D. James"] },
];

export const mysteryThrillerCatalog = buildCatalog(
  "Mystery & Thriller",
  entries,
);

export default mysteryThrillerCatalog;
