import type { CuratedCatalogEntry } from "./build";
import { buildCatalog } from "./build";

const entries: CuratedCatalogEntry[] = [
  { title: "Sapiens", authors: ["Yuval Noah Harari"] },
  { title: "Homo Deus", authors: ["Yuval Noah Harari"] },
  { title: "21 Lessons for the 21st Century", authors: ["Yuval Noah Harari"] },
  { title: "Educated", authors: ["Tara Westover"] },
  { title: "Becoming", authors: ["Michelle Obama"] },
  { title: "The Immortal Life of Henrietta Lacks", authors: ["Rebecca Skloot"] },
  { title: "The Wright Brothers", authors: ["David McCullough"] },
  { title: "Unbroken", authors: ["Laura Hillenbrand"] },
  { title: "Into Thin Air", authors: ["Jon Krakauer"] },
  { title: "Into the Wild", authors: ["Jon Krakauer"] },
  { title: "Born a Crime", authors: ["Trevor Noah"] },
  { title: "Atomic Habits", authors: ["James Clear"] },
  { title: "Thinking, Fast and Slow", authors: ["Daniel Kahneman"] },
  { title: "Man's Search for Meaning", authors: ["Viktor E. Frankl"] },
  { title: "Meditations", authors: ["Marcus Aurelius"] },
  { title: "The Diary of a Young Girl", authors: ["Anne Frank"] },
  { title: "The Art of War", authors: ["Sun Tzu"] },
  { title: "The Prince", authors: ["Niccolo Machiavelli"] },
  { title: "The Souls of Black Folk", authors: ["W. E. B. Du Bois"] },
  { title: "Silent Spring", authors: ["Rachel Carson"] },
  { title: "The Selfish Gene", authors: ["Richard Dawkins"] },
  { title: "A Brief History of Time", authors: ["Stephen Hawking"] },
  { title: "Cosmos", authors: ["Carl Sagan"] },
  { title: "The Gene", authors: ["Siddhartha Mukherjee"] },
  { title: "The Emperor of All Maladies", authors: ["Siddhartha Mukherjee"] },
  { title: "Guns, Germs, and Steel", authors: ["Jared Diamond"] },
  { title: "The Sixth Extinction", authors: ["Elizabeth Kolbert"] },
  { title: "The Body", authors: ["Bill Bryson"] },
  { title: "The Warmth of Other Suns", authors: ["Isabel Wilkerson"] },
  { title: "Killers of the Flower Moon", authors: ["David Grann"] },
  { title: "Hidden Figures", authors: ["Margot Lee Shetterly"] },
  { title: "Bad Blood", authors: ["John Carreyrou"] },
  { title: "Empire of Pain", authors: ["Patrick Radden Keefe"] },
  { title: "Say Nothing", authors: ["Patrick Radden Keefe"] },
  { title: "The Wager", authors: ["David Grann"] },
  { title: "Endurance", authors: ["Alfred Lansing"] },
  { title: "The Right Stuff", authors: ["Tom Wolfe"] },
  { title: "The Power Broker", authors: ["Robert A. Caro"] },
  { title: "Team of Rivals", authors: ["Doris Kearns Goodwin"] },
  { title: "The Looming Tower", authors: ["Lawrence Wright"] },
  { title: "Command and Control", authors: ["Eric Schlosser"] },
  { title: "The New Jim Crow", authors: ["Michelle Alexander"] },
  { title: "Evicted", authors: ["Matthew Desmond"] },
  { title: "Just Mercy", authors: ["Bryan Stevenson"] },
  { title: "Caste", authors: ["Isabel Wilkerson"] },
  { title: "Between the World and Me", authors: ["Ta-Nehisi Coates"] },
  { title: "Why Nations Fail", authors: ["Daron Acemoglu", "James A. Robinson"] },
  { title: "Freakonomics", authors: ["Steven D. Levitt", "Stephen J. Dubner"] },
  { title: "Outliers", authors: ["Malcolm Gladwell"] },
  { title: "The Tipping Point", authors: ["Malcolm Gladwell"] },
  { title: "The Black Swan", authors: ["Nassim Nicholas Taleb"] },
  { title: "Antifragile", authors: ["Nassim Nicholas Taleb"] },
  { title: "Predictably Irrational", authors: ["Dan Ariely"] },
  { title: "Nudge", authors: ["Richard H. Thaler", "Cass R. Sunstein"] },
  { title: "The Omnivore's Dilemma", authors: ["Michael Pollan"] },
  { title: "The Botany of Desire", authors: ["Michael Pollan"] },
  { title: "Salt", authors: ["Mark Kurlansky"] },
  { title: "Stiff", authors: ["Mary Roach"] },
  { title: "Quiet", authors: ["Susan Cain"] },
  { title: "Grit", authors: ["Angela Duckworth"] },
  { title: "Deep Work", authors: ["Cal Newport"] },
  { title: "The Righteous Mind", authors: ["Jonathan Haidt"] },
  { title: "The Road to Character", authors: ["David Brooks"] },
  { title: "The Undoing Project", authors: ["Michael Lewis"] },
  { title: "Surely You're Joking, Mr. Feynman!", authors: ["Richard P. Feynman"] },
  { title: "Longitude", authors: ["Dava Sobel"] },
  { title: "Seabiscuit", authors: ["Laura Hillenbrand"] },
  { title: "The Devil in the White City", authors: ["Erik Larson"] },
  { title: "The Hot Zone", authors: ["Richard Preston"] },
  { title: "The Spirit Catches You and You Fall Down", authors: ["Anne Fadiman"] },
  { title: "The Year of Magical Thinking", authors: ["Joan Didion"] },
  { title: "On Writing", authors: ["Stephen King"] },
  { title: "Bird by Bird", authors: ["Anne Lamott"] },
  { title: "Slouching Towards Bethlehem", authors: ["Joan Didion"] },
  { title: "The Fire Next Time", authors: ["James Baldwin"] },
  { title: "Notes of a Native Son", authors: ["James Baldwin"] },
  { title: "The Second Sex", authors: ["Simone de Beauvoir"] },
  { title: "A Room of One's Own", authors: ["Virginia Woolf"] },
  { title: "The Feminine Mystique", authors: ["Betty Friedan"] },
  { title: "The Autobiography of Malcolm X", authors: ["Malcolm X", "Alex Haley"] },
  { title: "Narrative of the Life of Frederick Douglass", authors: ["Frederick Douglass"] },
  { title: "I Know Why the Caged Bird Sings", authors: ["Maya Angelou"] },
  { title: "Angela's Ashes", authors: ["Frank McCourt"] },
  { title: "Kitchen Confidential", authors: ["Anthony Bourdain"] },
  { title: "Shoe Dog", authors: ["Phil Knight"] },
  { title: "Steve Jobs", authors: ["Walter Isaacson"] },
  { title: "Titan", authors: ["Ron Chernow"] },
  { title: "Leonardo da Vinci", authors: ["Walter Isaacson"] },
  { title: "The Rise and Fall of the Third Reich", authors: ["William L. Shirer"] },
  { title: "Bury My Heart at Wounded Knee", authors: ["Dee Brown"] },
  { title: "The Gulag Archipelago", authors: ["Aleksandr Solzhenitsyn"] },
  { title: "The Autobiography of Benjamin Franklin", authors: ["Benjamin Franklin"] },
  { title: "The Professor and the Madman", authors: ["Simon Winchester"] },
  { title: "In Cold Blood", authors: ["Truman Capote"] },
  { title: "The Glass Castle", authors: ["Jeannette Walls"] },
  { title: "H is for Hawk", authors: ["Helen Macdonald"] },
  { title: "When Breath Becomes Air", authors: ["Paul Kalanithi"] },
  { title: "Braiding Sweetgrass", authors: ["Robin Wall Kimmerer"] },
  { title: "The Splendid and the Vile", authors: ["Erik Larson"] },
  { title: "The Boys in the Boat", authors: ["Daniel James Brown"] },
];

export const nonFictionCatalog = buildCatalog("Non-Fiction", entries);

export default nonFictionCatalog;
