import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BookOpen from "lucide-react/dist/esm/icons/book-open.js";
import { cookies } from "next/headers";
import { Container } from "@/design/layout/grid";
import { darkThemeClass, lightThemeClass } from "@/design/tokens";
import { ThemeToggle } from "../design/theme/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Server: read cookie preference ('light' | 'dark')
  const cookieStore = await cookies();
  const pref = cookieStore.get("theme")?.value as "light" | "dark" | undefined;
  const themeClass = pref === "dark" ? darkThemeClass : lightThemeClass;
  const initialThemeAttr = pref ?? "light";
  return (
    <html lang="en" data-theme={initialThemeAttr}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${themeClass} font-sans`}
      >
        <header className="fixed inset-x-0 top-0 z-[100] border-b border-[color:var(--color-outline)] bg-[color:color-mix(in_srgb,var(--color-background)_94%,white_6%)] text-[var(--color-on-surface)]">
          <Container>
            <div className="flex min-h-14 items-center justify-between px-[var(--spacing-1)] sm:px-[var(--spacing-2)]">
              <div className="inline-flex items-center gap-[0.7rem] text-[1.05rem] font-bold tracking-[0.15px] text-[var(--color-on-background)]">
                <BookOpen
                  className="h-5 w-5 text-[var(--color-primary)]"
                  aria-hidden
                />
                Bukie
              </div>
              <ThemeToggle />
            </div>
          </Container>
        </header>
        {/* offset for fixed header */}
        <div className="h-14" aria-hidden />
        {children}
        <footer className="relative z-[1] mt-0 bg-[var(--color-background)] text-[var(--color-on-surface)]">
          <Container>
            <div className="flex items-center justify-center gap-[var(--spacing-1)] px-0 py-[var(--spacing-2)] text-center text-[var(--type-lg)] font-bold tracking-[0.2px] md:py-[var(--spacing-3)]">
              <BookOpen
                className="h-5 w-5 text-[var(--color-primary)]"
                aria-hidden
              />
              Bukie
            </div>
          </Container>
        </footer>
      </body>
    </html>
  );
}
