name: Biome Lint & Format

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run Biome check
        run: bunx biome check .
