name: Qlty.sh Coverage & Quality

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  qlty:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC authentication
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run Vitest with coverage
        run: bun run test --coverage
      - name: Upload coverage to Qlty.sh
        uses: qltysh/qlty-action/coverage@v1
        with:
          oidc: true
          files: coverage/lcov.info