name: Storybook Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  storybook-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Install Playwright Browsers
        run: bunx playwright install
      - name: Run Storybook Vitest tests
        run: bun run test:storybook
